### ISSUE TITLE
 Error TypeError: Illegal invocation on global window functions...

### ISSUE THREAD

**Issue by JensLincke** [LivelyKernel/lively.vm#5]
I know this is bad code but it should run anyway, or shouldn't it?

``` JS
var a = prompt('Hello', 'world');

// -> Error TypeError: Illegal invocation

// vs.

var b = window.prompt('Hello', 'world')
```

**Comment by rksm** [comment]
yes, it should but some functions are "special", this depends on the browser. We have a blacklist for those: https://github.com/LivelyKernel/lively.modules/blob/master/src/module.js#L247

I added prompt to it in lively.modules@0.5.31.

If there are more of these things we will make the rewrite config easier to modify.
